### PR TITLE
5.10 rn

### PR DESCRIPTION
**Pull request by loveshack**
These are corrections of things I noticed as I read through this part of the docs for the 5.10 release. Some of them re-phrase common continental grammar to native English.
I hope that's helpful, and it's OK to provide them all together. (I've just merged them on the one-5.10 branch, so I don't know why they're marked as not mergable.)

### CODE REVIEW

**Comment by tinova** [comment]
Thanks a lot loveshack! Hugely appreciate this.

master branch is now set for the next stable release (5.12). So release notes are now 'blank' in that branch, and the corrections for release notes on 5.10 should go on "one-5.10" branch. I'll cherry-pick the other file changes to one-5.10, but changes to release notes specific to 5.10 cannot be merged in master and are therefore lost, I'll manually add them to one-5.10.

**Comment by loveshack** [comment]
I'm puzzled -- I thought I had done this against the one-5.10 branch
which I was reading; I dislike git...

Anyway, I'll provide more as I re-read the docs.  They're minor changes,
of course, but may slightly improve ONE's appearance to native speakers
(who don't mind American spelling!).

**Comment by tinova** [comment]
I think the issue was creating the PR against master.

In any case, thanks again! We deeply appreciate the contribution, and welcome any further changes :)

**Comment by albert0marti** [comment]
Many thanks for your help with this, @loveshack

**Pull request merged**
