### PR TITLE
M #-: Fix permissions of /etc/one backup upgrading

### PR DESCRIPTION
**Pull request by rdiaz-on**

### CODE REVIEW

**Comment by vholer** [comment]
The correct way is to use `cp -a` to preserve permissions.

**Comment by rdiaz-on** [comment]
> The correct way is to use `cp -a` to preserve permissions.

done

**Comment by vholer** [comment]
Can you pls update also first command for /etc/one?
On etc restore, it's also good to have preserved owners / permissions.

**Comment by rdiaz-on** [comment]
> Can you pls update also first command for /etc/one?
> On etc restore, it's also good to have preserved owners / permissions.

done

**Pull request merged**
