### PR TITLE
fixed some systemd service names to fit current CentOS 7 version

### PR DESCRIPTION
**Pull request by JOJ0**
just installed 4.14 on centos 7 and did some minor corrections in the quickstart guide. thanks for merging.

### CODE REVIEW

**Comment by jmelis** [comment]
Hi, thanks for the PR!

Can you clarify a couple of things?

- The frontend is acting as nfs server, not only as an nfs client. After adding the exports to /etc/exports, shouldn't we indeed refresh (or reload) the nfs service, and not the nfs-client service, as we want to make  those exports available at a server level so nfs clients can mount it? What was the reason of changing nfs to nfs-client?

- The proposed pull request is a bit confusing regarding the dbus.service. You mention that it's activated by default, and that it can't be enabled of disabled manually. Then you ask to check if it's running, and then what? what should the user do if it's running and what should he do if it's not running? this last part is missing.

**Comment by JOJ0** [comment]
Hi, thanks for the reply!
 
- My changes are in Chapter "Step 2. Installation in the Nodes", we are not talking about the Frontend.

- Just to clarify: You can't "systemctl enable/disable dbus" but you _can_ "systemctl start/stop dbus". If dbus is not running, it must have been stopped by someone/something. You are right I should just add that the user should "systemctl start dbus.service" if it is not running. I am going to add that and update this pull request.

**Comment by JOJ0** [comment]
Hi again,
regarding the first point you stated: in the first instance of nfs.service on line 128,  it should not be changed to nfs-client.target. You are right. That was a mistake. Sorry. The second time, the change is correct. I will correct that as well in the updatet pull request.

**Comment by JOJ0** [comment]
Hi, you find the changes in commit 8d158fe.
Please ignore the 2 unneccessary commits 7aedb5f and e223965.
thank you

**Comment by jmelis** [comment]
thanks! merged!

**Pull request merged**
