### PR TITLE
Include Sunstone remote auth doc and  apache+passenger+kerberos example

### PR DESCRIPTION
**Pull request by alvarosimon**
This doc PR is related with https://github.com/OpenNebula/one/pull/71, how to Kerberize Sunstone service using remote auth.

### CODE REVIEW

**Comment by jfontan** [comment]
Cherry picked to branches one-4.14.1 (this should be 4.14.2) and master. Thank you!

**Comment by alvarosimon** [comment]
thanks a lot!

**Comment by rsmontero** [comment]
Hi Alvaro

Needing to set x509 for remote Auth is something that we'd like to polish. We propose the following approach.

* Users are created with public driver. The public driver disables the access of the users directly to the XML-RPC API (and SunstoneCloudAuth.rb). This way kerberos users cannot acces the core API. I assume this is the purpose of this change. 

```
$ oneuser create publicuser "new_user@DOMAIN"
```

* Update RemoteCloudAuth.rb to use a get_remote_username method instead  of get_username. This method will be included in CloudAuth.rb:
```ruby
 def get_remote_username(password)                                                                 
        @lock.synchronize do                                                                   
            @user_pool.each_with_xpath(                                                        
                "USER[contains(PASSWORD, \"#{password}\")]") do |user|                         
                return user["NAME"] if user["AUTH_DRIVER"] == "public" &&                        
                    user["PASSWORD"] == password
            end                                                                                
        end                                                                                                         
        nil                                                                                       
 end      
```

What do you think?

**Comment by alvarosimon** [comment]
Hi @rsmontero 

Great!, this is even better! yes I have used `x509` driver to include the remote user because I didn't find another way to auth the user, but if you include a generic driver like `publicuser` that will solve this issue. (and we avoid to use `x509` that could be a bit confusing). And of course this driver could be used by Kerberos or any other external auth mechanism handled by the web server.

**Comment by alvarosimon** [comment]
$ oneuser create publicuser "new_user@DOMAIN"

just one question, when you use `publicuser` driver you assume that the username and passwd are the same right?

**Comment by rsmontero** [comment]
sorry is just an auth method.  They maybe different

**Comment by alvarosimon** [comment]
ah ok that's fine, in our case we can have something like this using public
AUTH_DRIVER:

># oneuser show 4
>USER 4
INFORMATION
>ID              : 4
>NAME            : vsc41206
>GROUP           : users
>PASSWORD        : vsc41206@HPC.UGENT.BE
>AUTH_DRIVER     : public
>ENABLED         : Yes

>USER
TEMPLATE
>SSH_PUBLIC_KEY="ssh-dss AAAAB3"

2015-11-19 12:07 GMT+01:00 Ruben S. Montero <notifications@github.com>:

> sorry is just an auth method. They maybe different

**Comment by rsmontero** [comment]
Hi Alvaro,

We've update CouldAuth.rb and RemoteAuth.rb to make use of a generic verification method. So now the "get_username" method is moved to each Auth class.

The modifications have been tested with x509 and they works. Could you review the new RemoteAuth method. You can grab the new files here:

* [CloudAuth.rb] (https://github.com/OpenNebula/one/blob/master/src/cloud/common/CloudAuth.rb)
* [RemoteAuth.rb] (https://github.com/OpenNebula/one/blob/master/src/cloud/common/CloudAuth/RemoteCloudAuth.rb)

Also the [new documentation is here](https://github.com/OpenNebula/docs/blob/d8ba3141ce42d160e5ea952324bc4a55e35d212b/source/administration/sunstone_gui/suns_auth.rst#remote-auth)

The specific commits if you are interested are:
https://github.com/OpenNebula/one/commit/fd6b67e721e79a263b2b0c6a8f06308ad2a9352e
https://github.com/OpenNebula/one/commit/bac205df9ba46e87aaff21393c10b7e744afafcc
https://github.com/OpenNebula/one/commit/dc399e0a441b50bb99c230ba79095775d1cf68e8

Thanks!!

**Comment by alvarosimon** [comment]
Hi Ruben

This is great!, We will try the new auth in our cluster testbed during the next days using Kerberos and `RemoteAuth`. Thanks a lot!

**Pull request closed without merging**
